name: Build All Platforms
on:
  push:
    branches: [ main ]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: npm install

      - name: Build Web Assets
        run: |
          chmod +x ./node_modules/.bin/cap
          npx cap copy

      - name: Build Android (APK & AAB)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug # بيطلع APK
          ./gradlew bundleRelease  # بيطلع AAB للمتجر

      - name: Upload Android Files
        uses: actions/upload-artifact@v4
        with:
          name: Android-Package
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/bundle/release/app-release.aab

  ios-build:
    runs-on: macos-latest # لازم ماك عشان الـ iOS
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      
      - name: Build iOS Project
        run: |
          npx cap copy ios
          # ملحوظة: بناء ملف IPA يحتاج شهادات مطور (Provisioning Profiles)
          # هنا هنكتفي بتجهيز المشروع عشان يكون جاهز للرفع