name: Build All Platforms
on:
  push:
    branches: [ main ]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/android@latest # دي اللي كانت ناقصة

      - name: Sync Android
        run: |
          chmod +x ./node_modules/.bin/cap
          npx cap sync android

      - name: Build Android (APK & AAB)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew bundleRelease

      - name: Upload Android Files
        uses: actions/upload-artifact@v4
        with:
          name: Android-Package
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/bundle/release/app-release.aab

  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/ios@latest # دي اللي كانت ناقصة
      
      - name: Build iOS Project
        run: |
          chmod +x ./node_modules/.bin/cap
          npx cap add ios || true
          npx cap sync ios